[package]
name = "hoper"
version = "0.1.0"
edition = "2021"

[dependencies]
bitset = "0.1.2"
dyn-clone = "1.0.17"
itertools = "0.14.0"
petgraph = "0.7.1"
rand = "0.8.5"
rayon = "1.10.0"
symbol_table = "0.4.0"
